language: scala
scala:
 - 2.11.6
jdk:
 - oraclejdk8
env:
 global:
  - TRAVIS_JDK_VERSION=oraclejdk8Thx!
script:
  - sbt "project squbs-pipeline" clean coverage test
  - sbt "project squbs-unicomplex" clean coverage test
  - sbt "project squbs-testkit" clean coverage test
  - sbt "project squbs-httpclient" clean coverage test
  - sbt "project squbs-actorregistry" clean coverage test
  - sbt "project squbs-actormonitor" clean coverage test
  - sbt "project squbs-timeoutpolicy" clean coverage test
  - sbt "project squbs-zkcluster" clean coverage test
  - sbt "project squbs-pattern" clean coverage test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
after_success:
 - >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
  sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6120fddea5fd58b6bc51
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false