language: scala
scala:
 - 2.11.6
jdk:
 - oraclejdk8
env:
 global:
  - TRAVIS_JDK_VERSION=oraclejdk8
script:
  - sbt clean update compile test
after_success:
 - >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
  sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6120fddea5fd58b6bc51
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false