language: scala
scala:
 - 2.11.6
jdk:
 - oraclejdk8
env:
 global:
  - TRAVIS_JDK_VERSION=oraclejdk8Thx!
  - secure: lLJI8arelI5LxQYcvAz28NpJbFuCPPFuGWsd+3/gDeOU+8ajHHTcrzqHBpH2lMRXm+oP1xIHODEUF6jhO7aiNsHIbgOW8GgfuS61Q0MahqkBkxJKTpx4yvs6REByTsA1EWBUVOt3vHD6iNHIRap0qeqoeb/kZxI7VYUkI/xC08SCEhZCkGIRuYfPfP2qJvxbssdhbOzeWtnyq4C1m8ZdcKzoLHPM5USH2yrTjNWujUgAapRHNCBPH6nlOCpFZDRq3OsUTxAoOvlO3CTmHbsHzubjikqfpIZVcq1Hjn6rp+7K8FgLRrFLlW7utnNfVvjWAUkg7zGKxhz10EQjUOrQDrhETbBZXqLAApenWN2P0QhvyXwbI05Mg/pMXjjuI/7QSKXhd88FDiFz47c8ad5SjJ8d3xHZgYhnBwEkh6XN4pIwuqx485d9PlvtfVLJ4g1YLlLXGHxZICfdN8oxqWhasqFLt06KjQFZN/OHQ7tzUIL+38WT/W/mN2aJXZau5KoFcIIfRnc8T4R3GDoNrVOkEYNNFYx2cHX5OlEQjz9KhtTSRun+dJOnAp1vPEVbJ+z8dNrWbJqMamRXtZfib7cR5MyCu0tcE1ZF50BVYLvC0IF6Rncblvvg62VEfivaAMD8mbuM+ZSfMEIQ3f+E+Pxe2S7YYokfJSwHkuLwtHYgKRc=
script:
  - sbt "< sbt-commands.txt"
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
after_success:
 - >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
  sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6120fddea5fd58b6bc51
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
